"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/css/index.css";
import "bootstrap/dist/css/bootstrap.min.css";
import React from "react";
import { MainNavbar } from "@/app/main-navbar.tsx";
import { SWRConfig } from "swr";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const fetcher = (url: string) => fetch(url).then((r) => r.json());

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader showSpinner={false} />
        <SWRConfig value={{ fetcher }}>
          <MainNavbar />
          {children}
        </SWRConfig>
      </body>
    </html>
  );
}
