"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/css/index.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "react-bootstrap/Navbar";
import Nav from "react-bootstrap/Nav";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar bg="light" expand="lg" className="px-3">
          <Navbar.Brand href=".">Year-Week-Day</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="mr-auto">
              <Nav.Link href="/">Home</Nav.Link>
              <Nav.Link href="https://github.com/spidgorny/year-week-day/issues">
                Problem/Suggestion?
              </Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Navbar>

        {children}
      </body>
    </html>
  );
}
